[package]
name = "alloyport-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
alloyport-core = { path = "../alloyport-core" }
alloyport-events = { path = "../alloyport-events" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
